local M = {
  config = nil,
  base_config = nil,
  dynamic_menus = {},
  dynamic_menu_order = {},
  active_top = 1,
  windows = {},
  buffers = {},
  menu_stack = {},
  pending_action = nil,
  pending_context = nil,
  menu_context = nil,
  last_visual_context = nil,
  last_visual_exit_ns = 0,
  menu_owner_win = nil,
  anchor = { row = nil, col = nil },
  label_positions = {},
  component_positions = {},
  menu_mode = false,
  global_mouse_installed = false,
  keymaps_installed = false,
  current_open_key = nil,
  last_refresh_signature = nil,
  mouse_trace_path = nil,
  mousemoveevent_was_enabled = nil,
  selection_namespace = vim.api.nvim_create_namespace("orca_menu_selection"),
  namespace = vim.api.nvim_create_namespace("orca_menu"),
}

return M
